public/stylesheets/inventory.css, views/inventory.html
Inventory webpage is partially done
=> Henrys feature/inventory

app.js, db.js, routes/user.js, views/user.ejs
- added db.js
- added displaying users' food data
=> Inventory routing

routes/user.js
add routing code for post request to /addFoodItem.
=> add routing code for addFoodItem.

public/stylesheets/main.css
Edited carousel size on main.css for index.ejs to look nice on all mobile device
=> Changes on main page

db.js, routes/user.js
=> applied change from using user's ID to user's email

public/javascripts/user.js, views/user.ejs
Added delete buttons prototype on item list page
=> Henrys feature/delete button

public/javascripts/dashboard.js, public/stylesheets/dashboard.css, routes/dashboard.js, views/dashboard.ejs
- added a delete feature
// The dashboard is currently not refreshed after deleting.
=> Added delete routing

routes/dashboard.js, views/dashboard.ejs
=> added "Add single item" feature

routes/dashboard.js
- modified add/delete feature for Azure
=> Modified add/delete feature

views/fridge.ejs
route of allfood post request in fridge.ejs has been changed.
=> fix 404 not found error in allfood post request

app.js, config/db.js, routes/fridge.js, routes/home.js
change db.login to db.getUserFoodData
all configuration file will be stored in config folder.
=> create 'config' folder for db.js and future use.

app.js, config/authLocal.js, config/db.js, routes/fridge.js, routes/home.js
- implements local authentication.
add modules in app.js and include configuration codes in the config/authLocal.js
delegate db.getUserFoodInfo login function to passport.
after user login, all user info will be stored in 'req.user' as form of
[ 
email: 'jaehh1987@gmail.com',
name: 'Jae, Hyunhyo',
password: '12345Jay',
alarm: null 
]
=> implements local authentication.

public/javascripts/fridge.js, routes/fridge.js, views/fridge.ejs
- fixed a bug on add a single item feature
- modified the easter egg a little
=> fixed add a single item feature & modified the easter egg a little

public/stylesheets/fridge.css, views/fridge.ejs
1. new font on fridge page
2. redesign a bit
3. deleted unused code
4. code indentation
=> Younhee feature

app.js, config/authLocal.js, node_modules/connect-flash/.travis.yml, node_modules/connect-flash/LICENSE, node_modules/connect-flash/README.md, node_modules/connect-flash/lib/flash.js, node_modules/connect-flash/lib/index.js, node_modules/connect-flash/package.json, package-lock.json, package.json, public/javascripts/fridge.js, public/javascripts/home.js, public/stylesheets/fridge.css, public/stylesheets/home.css, routes/fridge.js, routes/home.js, views/home.ejs
=> Feature flash

routes/fridge.js, views/fridge.ejs
- Added notification routing to store a value on "alarm" column on users table
=> Added notification routing

routes/fridge.js
- Put code that calculates daysLeft in a function
=> Feature/organize daysLeft calculation code

public/stylesheets/fridge.css, views/fridge.ejs
=> Younhee feature/progress bar

views/fridge.ejs
- fixed a progress bar percentage
=> fixed a progress bar's percentage

views/fridge.ejs
little modify for the placement on the notification button and linked in font awesome, only these two since Uni took my work...
=> linked in font awesome and readjust the notification button

app.js, config/auth.js, routes/fridge.js, routes/home.js, views/home.ejs
move authentication related routers from fridge.js to home.js
add google register function.
modify local register router to redirect user directly to fridge page
=> modify authentication related code

app.js, config/auth.js
modify authentication code to enable heroku register and login
=> Heroku auth

config/db.js, daily.js
=> Fixed updateDaysLeft error

public/javascripts/fridge.js, public/javascripts/scanner.js, public/stylesheets/fridge.css, views/fridge.ejs
Looks like more mobile friendly as ever
=> Henrys feature/uni deleteand header js

public/javascripts/fridge.js
=> Fixed a delete an item feature

public/stylesheets/fridge.css
=> Younhee feature/background

public/stylesheets/fridge.css, routes/fridge.js, views/fridge.ejs
1. delete unused css
2.  simple retouching on logout button
=> Younhee feature/logout2

config/auth.js
correct google auth error in auth.js
=> correct small error in google login

public/javascripts/scanner.js, views/fridge.ejs
closed divs and checked, it is fine
=> adjustments from fix3
